#!/usr/bin/env python3
"""Generate visuals for queued posts via the OpenAI Images API (gpt-image-2).

Reads today's queue/<date>.json and renders a branded image for every post whose
visual.source == "openai", dispatching on the post's "format" field:

  * single  -> one image at assets/generated/<id>.png (visual.file)
  * story   -> one 9:16 frame (defaults to vertical) at the same path
  * reel    -> one 9:16 base still; scripts/reel_gen.py later animates it to mp4
  * carousel-> one image per visual.slides[] entry at assets/generated/<id>-<n>.png
               (visual.files is the ordered list; visual.file is the cover)

gpt-image-2 was chosen over the previous Higgsfield backend for its consistency
across this brand's cinematic, Afrofuturistic visual system. Prompts are still
composed per brand/visual-style.md (base prompt + add-on + scene + negative
prompt) by the generation step before this script runs.

After each image renders, the script composites branded typography onto it
(infographic / title-card style): a Bebas Neue headline + optional Inter
supporting line from the post's visual.headline / visual.subtext fields. The
image models are prompted NOT to render text
(theirs is garbled), so all on-image type is laid down here with bundled fonts
under assets/fonts/.

Manual (no-API) mode: pass ``--manual`` (or set ``IMAGE_BACKEND=manual``) to skip
the API entirely. Instead of rendering, the script writes a copy-paste prompt pack
to ``queue/<name>.prompts.md`` so the images can be generated by hand in ChatGPT /
Copilot and finished with ``scripts/manual_media_ingest.py``. The same happens
automatically when no image credentials are configured, so a run never dies (or
silently degrades every post to "library") just because there's no key.

Requires: pip install openai requests pillow
  (manual mode and the ingest script need Pillow only — the openai package is
  imported lazily so a no-API install still works.)
Env vars:
  * Direct OpenAI (default):  OPENAI_API_KEY
  * Azure OpenAI (preferred when set): AZURE_OPENAI_ENDPOINT,
    AZURE_OPENAI_API_KEY, AZURE_OPENAI_IMAGE_DEPLOYMENT, and optionally
    AZURE_OPENAI_API_VERSION. When all three required Azure vars are present the
    script uses Azure OpenAI; otherwise it falls back to direct OpenAI.
  * IMAGE_BACKEND=manual forces the no-API prompt-pack mode.
"""
import argparse
import base64
import json
import math
import os
import string
import pathlib
from PIL import (Image, ImageChops, ImageDraw, ImageFilter, ImageFont, ImageOps,
                 ImageStat)

import manual_media

# The openai SDK is only needed to actually call an image API. Manual mode and
# scripts/manual_media_ingest.py (which reuses the typography renderers below)
# must run on a Pillow-only install, so the import is optional.
try:
    from openai import OpenAI, AzureOpenAI, OpenAIError
    OPENAI_SDK_AVAILABLE = True
except ImportError:  # pragma: no cover - exercised by no-API installs
    OpenAI = AzureOpenAI = None
    OPENAI_SDK_AVAILABLE = False

    class OpenAIError(Exception):
        """Stand-in so the API error handling below still parses without the SDK."""

# ---------------------------------------------------------------------------
# OpenAI image model.
#
# gpt-image-2 returns base64-encoded PNG bytes (result.data[0].b64_json), NOT a
# URL. It supports a fixed set of canvas sizes; we map the brand aspect ratios
# to the closest supported portrait/landscape/square size below.
# ---------------------------------------------------------------------------
IMAGE_MODEL = os.environ.get("OPENAI_IMAGE_MODEL", "gpt-image-2")
# Quality tier: "low" (drafts), "medium", "high" (hero assets). The module
# default is "high" (the Azure benefit is uncharged, so favour quality); a post
# can still set visual.quality per item to "low"/"medium" for drafts. An empty
# OPENAI_IMAGE_QUALITY (e.g. an unset Actions variable) falls back to "high".
IMAGE_QUALITY = (os.environ.get("OPENAI_IMAGE_QUALITY") or "high").strip().lower()
VALID_QUALITIES = {"low", "medium", "high"}
if IMAGE_QUALITY not in VALID_QUALITIES:
    IMAGE_QUALITY = "high"
# Brand aspect ratio -> gpt-image-2 supported canvas size.
ASPECT_SIZE = {
    "1:1": "1024x1024",
    "9:16": "1024x1536",   # portrait
    "16:9": "1536x1024",   # landscape
}
DEFAULT_SIZE = "1024x1024"

# 2K master: gpt-image-2 caps natively at a 1536px long edge, so we LANCZOS-
# upscale each rendered still to IMAGE_LONG_EDGE (default 2048) *before*
# compositing brand type, keeping typography crisp at full resolution.
# Aspect ratio is preserved. Disable with OPENAI_IMAGE_2K=0 (empty/unset = on).
IMAGE_2K = os.environ.get("OPENAI_IMAGE_2K", "1").strip().lower() not in (
    "0", "false", "no", "off")
try:
    IMAGE_LONG_EDGE = int(os.environ.get("OPENAI_IMAGE_LONG_EDGE") or "2048")
except ValueError:
    IMAGE_LONG_EDGE = 2048

# ---------------------------------------------------------------------------
# Image backend selection: Azure OpenAI (preferred when configured) or direct
# OpenAI (fallback). The openai SDK ships both clients, so this adds no new
# dependency. On Azure the model passed to the Images API must be the
# *deployment name*, not "gpt-image-2"; everything else (generate/edit, the
# b64_json response, supported sizes, and quality tiers) is identical across the
# two backends.
# ---------------------------------------------------------------------------
AZURE_OPENAI_ENDPOINT = os.environ.get("AZURE_OPENAI_ENDPOINT", "").strip()
AZURE_OPENAI_API_KEY = os.environ.get("AZURE_OPENAI_API_KEY", "").strip()
AZURE_OPENAI_IMAGE_DEPLOYMENT = os.environ.get(
    "AZURE_OPENAI_IMAGE_DEPLOYMENT", "").strip()
# api-version that supports gpt-image generation/edits; override per deployment.
AZURE_OPENAI_API_VERSION = os.environ.get(
    "AZURE_OPENAI_API_VERSION", "2025-04-01-preview").strip()
# Manual (no-API) mode: emit a copy-paste prompt pack instead of calling an API.
MANUAL_BACKEND = os.environ.get("IMAGE_BACKEND", "").strip().lower() == "manual"


def azure_configured() -> bool:
    return bool(AZURE_OPENAI_ENDPOINT and AZURE_OPENAI_API_KEY
                and AZURE_OPENAI_IMAGE_DEPLOYMENT)


def image_backend_available() -> bool:
    """True when this run can actually reach an image API.

    Requires the openai SDK plus either the Azure trio or an OPENAI_API_KEY.
    When it's False the script falls back to manual mode instead of failing.
    """
    if not OPENAI_SDK_AVAILABLE:
        return False
    return azure_configured() or bool(os.environ.get("OPENAI_API_KEY", "").strip())


def _make_image_client():
    """Build the Images API client and resolve the model identifier to use.

    Returns ``(client, model_name)``. When the Azure OpenAI env vars (endpoint +
    key + deployment) are all set we use ``AzureOpenAI`` and the *deployment
    name* as the model; otherwise we fall back to direct ``OpenAI()`` (reading
    ``OPENAI_API_KEY``) with the configured ``IMAGE_MODEL``. Behaviour is
    identical to before when Azure isn't configured.
    """
    if azure_configured():
        client = AzureOpenAI(
            azure_endpoint=AZURE_OPENAI_ENDPOINT,
            api_key=AZURE_OPENAI_API_KEY,
            api_version=AZURE_OPENAI_API_VERSION,
        )
        print(f"Using Azure OpenAI image backend "
              f"(deployment={AZURE_OPENAI_IMAGE_DEPLOYMENT}, "
              f"api_version={AZURE_OPENAI_API_VERSION})")
        return client, AZURE_OPENAI_IMAGE_DEPLOYMENT
    client = OpenAI()
    print(f"Using direct OpenAI image backend (model={IMAGE_MODEL})")
    return client, IMAGE_MODEL


# --- Branding composite -----------------------------------------------------
# After each image is generated, the engine composites brand typography. The
# image models are prompted NOT to render text; see brand/visual-style.md.
# Wordmark compositing is disabled by default per current brand direction.
WORDMARK_PATH = pathlib.Path("assets/library/layer8-wordmark.png")
# Wordmark width as a fraction of the base image width, tuned per aspect ratio
# (taller/narrower formats get a slightly larger mark for legibility).
LOGO_WIDTH_FRAC = {"1:1": 0.26, "9:16": 0.40, "16:9": 0.20}
LOGO_MARGIN_FRAC = 0.04  # margin from the edges, as a fraction of base width
DEFAULT_LOGO_POSITION = "top-right"
# Per-account default wordmark placement. Kept for backwards-compatible queue
# parsing, but no wordmark asset is applied while ACCOUNT_WORDMARK maps to None.
ACCOUNT_LOGO_POSITION = {
    "layer8culture": "top-right",
    "lofi": "top-right",
}
# Per-account wordmark asset. None means no wordmark is composited for that
# account. Accounts not listed also skip the wordmark.
ACCOUNT_WORDMARK = {
    "layer8culture": None,
    "lofi": None,
}
# Wordmark opacity support is retained only for backwards-compatible queue parsing.
DEFAULT_LOGO_OPACITY = 1.0
SUBTLE_LOGO_OPACITY = 0.55


def composite_wordmark(
    image_path: pathlib.Path,
    aspect: str,
    position: str,
    opacity: float = DEFAULT_LOGO_OPACITY,
    wordmark_path: pathlib.Path | None = WORDMARK_PATH,
) -> bool:
    """Overlay a wordmark onto a generated image in place.

    No-op (returns False) if ``wordmark_path`` is None (the account has no
    wordmark) or the asset is missing. ``position`` is one of top-left,
    top-right, bottom-left, bottom-right, center. ``opacity`` scales the
    wordmark's alpha channel (1.0 = opaque, lower = subtle). Returns True
    when the wordmark was composited.
    """
    if wordmark_path is None or not wordmark_path.exists():
        return False
    opacity = max(0.0, min(1.0, opacity))
    base = Image.open(image_path).convert("RGBA")
    logo = Image.open(wordmark_path).convert("RGBA")
    bw, bh = base.size
    target_w = max(1, int(bw * LOGO_WIDTH_FRAC.get(aspect, 0.26)))
    scale = target_w / logo.width
    logo = logo.resize((target_w, max(1, int(logo.height * scale))), Image.LANCZOS)
    if opacity < 1.0:
        alpha = logo.getchannel("A").point(lambda a: int(a * opacity))
        logo.putalpha(alpha)
    lw, lh = logo.size
    margin = int(bw * LOGO_MARGIN_FRAC)
    positions = {
        "top-left": (margin, margin),
        "top-right": (bw - lw - margin, margin),
        "bottom-left": (margin, bh - lh - margin),
        "bottom-right": (bw - lw - margin, bh - lh - margin),
        "center": ((bw - lw) // 2, (bh - lh) // 2),
    }
    pos = positions.get(position, positions[DEFAULT_LOGO_POSITION])
    base.alpha_composite(logo, pos)
    base.convert("RGB").save(image_path)
    return True


# --- Infographic typography overlay -----------------------------------------
# The image models are prompted NOT to render text (their typography is garbled);
# instead we composite clean, on-brand headline typography onto each image. Main
# Layer8Culture posts use Bebas Neue headlines across both title-card and Editorial
# Drop layouts. Supporting copy uses Inter. Colors follow the brand system. Fonts
# are OFL-licensed and bundled under assets/fonts.
FONTS_DIR = pathlib.Path("assets/fonts")
SPACE_GROTESK_PATH = FONTS_DIR / "SpaceGrotesk-Variable.ttf"
INTER_PATH = FONTS_DIR / "Inter-Variable.ttf"
BEBAS_NEUE_PATH = FONTS_DIR / "BebasNeue-Regular.ttf"
SOFT_WHITE = (245, 245, 245, 255)
ELECTRIC_BLUE = (0, 71, 255, 255)
EDITORIAL_DIM = (180, 190, 200, 255)
# Where the headline block sits. "lower-left" reads like a title card; the prompt
# is told to keep that region as clean negative space.
DEFAULT_OVERLAY_POSITION = "lower-left"


def _load_font(path: pathlib.Path, size: int, instance: str) -> ImageFont.FreeTypeFont:
    font = ImageFont.truetype(str(path), size)
    try:
        font.set_variation_by_name(instance)
    except Exception:  # noqa: BLE001 - static fallback if no named instance
        pass
    return font


def _line_width(draw: ImageDraw.ImageDraw, text: str, font, tracking: float) -> float:
    if not text:
        return 0.0
    return sum(draw.textlength(ch, font=font) for ch in text) + tracking * (len(text) - 1)


def _wrap(draw, text: str, font, max_w: float, tracking: float) -> list[str]:
    lines: list[str] = []
    current = ""
    for word in text.split():
        trial = word if not current else f"{current} {word}"
        if not current or _line_width(draw, trial, font, tracking) <= max_w:
            current = trial
        else:
            lines.append(current)
            current = word
    if current:
        lines.append(current)
    return lines


def _fit_headline(draw, text, max_w, start_size, min_size, max_lines):
    """Shrink the headline font until it wraps to <= max_lines within max_w."""
    size = start_size
    while size >= min_size:
        font = _load_font(SPACE_GROTESK_PATH, size, "Bold")
        tracking = size * 0.03
        lines = _wrap(draw, text, font, max_w, tracking)
        if len(lines) <= max_lines:
            return font, size, tracking, lines
        size -= 2
    font = _load_font(SPACE_GROTESK_PATH, min_size, "Bold")
    tracking = min_size * 0.03
    return font, min_size, tracking, _wrap(draw, text, font, max_w, tracking)


def _balance_lines(draw, text: str, font, max_w: float, tracking: float,
                   lines: list[str]) -> list[str]:
    """Re-wrap ``text`` to the same line count with the lines evened out.

    Greedy wrapping packs each line to the margin and leaves the remainder on the
    last one, so "ONE DRIVER, ANY DEVICE" breaks as "ONE DRIVER, ANY / DEVICE" and
    strands a single word. Narrowing the measure until the line count is about to
    grow finds the most even break for the same number of lines, which is what a
    premium editorial card needs.
    """
    if len(lines) < 2:
        return lines
    widths = [_line_width(draw, word, font, tracking) for word in text.split()]
    lo, hi = (max(widths) if widths else 0.0), float(max_w)
    best = lines
    while hi - lo > 1.0:
        mid = (lo + hi) / 2
        candidate = _wrap(draw, text, font, mid, tracking)
        if len(candidate) <= len(lines):
            best, hi = candidate, mid
        else:
            lo = mid
    return best


def _type_scale(w: int, h: int) -> float:
    """Reference dimension for sizing type on a frame of ``w x h``.

    Sizing purely off width under-sets portrait frames: a 9:16 master is 1152
    wide against 2048 of height, so a headline scaled from width lands at ~4.8%
    of frame height where the same rule gives 8.5% on a 1:1 master. The geometric
    mean tracks the frame's actual visual area instead, and is exactly ``w`` when
    ``w == h``, so square posts render identically to before.
    """
    return math.sqrt(float(w) * float(h))


def _block_bottom(y: int, font, tracking: float, lines: list[str]) -> int:
    """Bottom of the ink for the last of ``lines`` drawn from ``y``.

    ``draw.text`` places the ascender at ``y`` and the glyph box extends below it,
    so a line's real footprint is taller than the leading used to advance between
    lines. Measuring it is what keeps a measured block height honest.
    """
    if not lines:
        return y
    try:
        return y + int(font.getbbox(lines[-1])[3])
    except Exception:  # noqa: BLE001 - fall back to the nominal font size
        return y + int(getattr(font, "size", 0))


# --------------------------------------------------------------------------
# The headline scrim
# --------------------------------------------------------------------------
# The scrim exists for one reason: keep the headline legible on any plate. It is
# sized to that job and nothing more. The previous version darkened the bottom
# 54-60% of the frame to 80-90% black regardless of what was underneath, which
# crushed already-dark art into a featureless void, and built its ramp with
# integer alpha per row, which banded into 5-6px stripes at the 2K master size.
SCRIM_TARGET_LUM = 64.0   # luminance we want the plate behind the headline to sit at
SCRIM_MIN_ALPHA = 38      # a whisper even on black art, so the type still feels seated
SCRIM_MAX_ALPHA = 200     # never crush the plate completely
SCRIM_RAMP_FRAC = 0.18    # ease-in height, as a fraction of image height
SCRIM_PERCENTILE = 0.85   # judge the plate by its highlights, not its average
# Legibility depends on how *busy* the plate is, not only how bright it is. A
# dark but detailed plate (rooftops, foliage, particles) gives white type nothing
# to separate from even though its luminance asks for almost no scrim. This adds
# a modest floor driven by local detail, capped so it can never crush the art.
SCRIM_DETAIL_GAIN = 16.0
SCRIM_DETAIL_DEADBAND = 1.8  # below this a plate is flat enough to need nothing
SCRIM_DETAIL_MAX = 46

# Editorial Drop layout constants.
# 4.5% left type 2.9% clear of the frame edge once the drift below was fixed,
# which is inside the UI overlay Instagram draws over the foot of a feed post.
EDITORIAL_BOTTOM_MARGIN = 0.075
SUB_MAX_LINES = 3
# Safety rail. A layout that puts its type near the top (top_text_media_card)
# would otherwise ask the scrim to cover the whole frame at full strength, which
# is a dimmer, not a scrim. Those layouts were never scrim-backed anyway.
SCRIM_MIN_TOP_FRAC = 0.35

# Ordered 8x8 Bayer thresholds. Deterministic (so the same input always renders
# the same bytes) and enough to break the 1/255 alpha steps into a fine
# crosshatch instead of straight horizontal edges.
_BAYER8 = (
    0, 32, 8, 40, 2, 34, 10, 42,
    48, 16, 56, 24, 50, 18, 58, 26,
    12, 44, 4, 36, 14, 46, 6, 38,
    60, 28, 52, 20, 62, 30, 54, 22,
    3, 35, 11, 43, 1, 33, 9, 41,
    51, 19, 59, 27, 49, 17, 57, 25,
    15, 47, 7, 39, 13, 45, 5, 37,
    63, 31, 55, 23, 61, 29, 53, 21,
)


def _bayer_field(w: int, h: int) -> Image.Image:
    """An ``w x h`` L-mode field of tiled Bayer thresholds."""
    tile = Image.new("L", (8, 8))
    tile.putdata([int((v + 0.5) * 255 / 64) for v in _BAYER8])
    strip = Image.new("L", (w, 8))
    for x in range(0, w, 8):
        strip.paste(tile, (x, 0))
    field = Image.new("L", (w, h))
    for y in range(0, h, 8):
        field.paste(strip, (0, y))
    return field


def _plate_luminance(base: Image.Image, y0: int,
                     percentile: float = SCRIM_PERCENTILE) -> float:
    """Luminance of the region the headline will sit on.

    A percentile rather than a mean: art that is mostly black but has one bright
    practical light still needs enough scrim for the type to survive crossing it.
    """
    w, h = base.size
    y0 = max(0, min(int(y0), h - 1))
    region = base.crop((0, y0, w, h)).convert("L")
    hist = region.histogram()
    total = sum(hist)
    if not total:
        return 0.0
    cutoff = total * percentile
    seen = 0
    for value, count in enumerate(hist):
        seen += count
        if seen >= cutoff:
            return float(value)
    return 255.0


def _plate_detail(base: Image.Image, y0: int) -> float:
    """How busy the region under the type is, as a high-pass standard deviation.

    Flat art scores near zero; art full of small edges scores high. This is the
    part of legibility that luminance alone misses.
    """
    w, h = base.size
    y0 = max(0, min(int(y0), h - 1))
    region = base.crop((0, y0, w, h)).convert("L")
    if region.width < 4 or region.height < 4:
        return 0.0
    blurred = region.filter(ImageFilter.GaussianBlur(2))
    return ImageStat.Stat(ImageChops.difference(region, blurred)).stddev[0]


def _scrim_peak_alpha(plate_lum: float, plate_detail: float = 0.0) -> int:
    """How much black the plate needs to reach SCRIM_TARGET_LUM.

    Compositing black at alpha ``a`` scales luminance by ``1 - a``, so the alpha
    that lands a plate of ``L`` on the target is ``1 - target/L``. Dark art asks
    for almost nothing and keeps its detail; bright art still gets a real scrim.
    ``plate_detail`` raises the floor for busy plates, which need separation even
    when they are already dark.
    """
    busy = max(0.0, plate_detail - SCRIM_DETAIL_DEADBAND)
    detail_floor = min(SCRIM_DETAIL_MAX, int(round(busy * SCRIM_DETAIL_GAIN)))
    floor = SCRIM_MIN_ALPHA + detail_floor
    if plate_lum <= 0:
        return min(SCRIM_MAX_ALPHA, floor)
    needed = 1.0 - (SCRIM_TARGET_LUM / plate_lum)
    alpha = int(round(max(0.0, needed) * 255))
    return max(floor, min(SCRIM_MAX_ALPHA, max(alpha, floor)))


def _scrim_alpha_map(w: int, h: int, text_top: int, peak: int) -> Image.Image:
    """Alpha channel for the scrim: eased in above the type, flat behind it.

    Holding a constant alpha behind the text (instead of ramping to maximum at
    the very bottom) is what keeps the plate even and stops the gradient from
    darkening far more of the frame than the type actually needs.
    """
    ramp = max(1, int(h * SCRIM_RAMP_FRAC))
    start = max(0, min(int(text_top), h) - ramp)
    floor_col = Image.new("L", (1, h), 0)
    frac_col = Image.new("L", (1, h), 0)
    floor_px = floor_col.load()
    frac_px = frac_col.load()
    for y in range(start, h):
        if y >= text_top:
            value = float(peak)
        else:
            t = (y - start) / float(ramp)
            value = peak * (t * t * (3.0 - 2.0 * t))  # smoothstep: no visible onset
        whole = int(value)
        floor_px[0, y] = min(255, whole)
        frac_px[0, y] = int(round((value - whole) * 255))
    floor_full = floor_col.resize((w, h), Image.NEAREST)
    frac_full = frac_col.resize((w, h), Image.NEAREST)
    # Promote a pixel to the next alpha step when its fractional part beats the
    # local Bayer threshold. That converts a hard band boundary into a dither.
    carry = ImageChops.subtract(frac_full, _bayer_field(w, h)).point(
        lambda v: 1 if v > 0 else 0)
    return ImageChops.add(floor_full, carry)


def _bottom_scrim(base: Image.Image, text_top: int | None = None) -> Image.Image:
    """Darken just enough behind the headline to keep it legible.

    ``text_top`` is the y the type block starts at; the scrim eases in above it
    and holds steady from there down.
    """
    if base.mode != "RGBA":
        base = base.convert("RGBA")
    w, h = base.size
    if text_top is None:
        text_top = int(h * 0.58)
    text_top = max(int(h * SCRIM_MIN_TOP_FRAC), min(int(text_top), h))
    peak = _scrim_peak_alpha(_plate_luminance(base, text_top),
                             _plate_detail(base, text_top))
    scrim = Image.new("RGBA", (w, h), (0, 0, 0, 0))
    scrim.putalpha(_scrim_alpha_map(w, h, text_top, peak))
    return Image.alpha_composite(base, scrim)


def _draw_tracked_line(draw, x, y, line, font, tracking, default_fill,
                       accent_tokens, accent_fill):
    """Draw a single line with letter tracking; words whose normalized form is in
    accent_tokens are rendered in the accent color."""
    cx = x
    space_w = draw.textlength(" ", font=font)
    words = line.split(" ")
    for wi, word in enumerate(words):
        norm = word.strip(string.punctuation).lower()
        fill = accent_fill if norm and norm in accent_tokens else default_fill
        for ch in word:
            draw.text((cx, y), ch, font=font, fill=fill)
            cx += draw.textlength(ch, font=font) + tracking
        if wi != len(words) - 1:
            cx += space_w + tracking


def render_infographic(image_path: pathlib.Path, headline: str,
                       subtext: str | None = None,
                       position: str = DEFAULT_OVERLAY_POSITION,
                       accent: str | None = None) -> bool:
    """Composite a branded headline (and optional supporting line) onto an image,
    infographic / title-card style. Returns False if the fonts are missing so
    generation never depends on the overlay."""
    if not (SPACE_GROTESK_PATH.exists() and INTER_PATH.exists()):
        return False
    base = Image.open(image_path).convert("RGBA")
    w, h = base.size
    draw = ImageDraw.Draw(base)

    margin = int(w * 0.07)
    max_w = w - 2 * margin
    scale = _type_scale(w, h)
    centered = position == "lower-center"

    accent_tokens = {t.strip(string.punctuation).lower()
                     for t in (accent or "").split() if t.strip(string.punctuation)}

    headline_text = headline.strip().upper()
    font_h, size_h, track_h, lines_h = _fit_headline(
        draw, headline_text, max_w,
        start_size=int(scale * 0.085), min_size=int(scale * 0.042), max_lines=3)
    if BEBAS_NEUE_PATH.exists():
        size = size_h
        while size >= int(scale * 0.040):
            candidate = ImageFont.truetype(str(BEBAS_NEUE_PATH), size)
            tracking = size * 0.005
            lines = _wrap(draw, headline_text, candidate, max_w, tracking)
            if len(lines) <= 3:
                font_h, size_h, track_h, lines_h = candidate, size, tracking, lines
                break
            size -= 2
    lines_h = _balance_lines(draw, headline_text, font_h, max_w, track_h, lines_h)
    hlh = int(size_h * 1.16)

    sub_lines: list[str] = []
    font_s = None
    size_s = 0
    track_s = 0.0
    if subtext:
        size_s = max(int(scale * 0.030), 18)
        font_s = _load_font(INTER_PATH, size_s, "Medium")
        track_s = size_s * 0.01
        sub_lines = _wrap(draw, subtext.strip(), font_s, max_w, track_s)
    slh = int(size_s * 1.35)

    accent_h = max(3, int(scale * 0.012))
    accent_w = int(scale * 0.10)
    accent_gap = int(size_h * 0.35)
    sub_gap = int(size_h * 0.28) if sub_lines else 0

    block_h = accent_h + accent_gap + len(lines_h) * hlh + sub_gap + len(sub_lines) * slh
    bottom_margin = int(h * 0.09)
    top = h - bottom_margin - block_h

    # Now that the type block is measured, darken only what sits under it. The
    # draw handle has to be rebuilt because alpha_composite returns a new image.
    base = _bottom_scrim(base, text_top=top)
    draw = ImageDraw.Draw(base)

    def line_x(line, font, tracking):
        if not centered:
            return margin
        return int((w - _line_width(draw, line, font, tracking)) / 2)

    # Electric-blue accent rule.
    bar_x = margin if not centered else int((w - accent_w) / 2)
    draw.rectangle([bar_x, top, bar_x + accent_w, top + accent_h], fill=ELECTRIC_BLUE)

    y = top + accent_h + accent_gap
    for line in lines_h:
        _draw_tracked_line(draw, line_x(line, font_h, track_h), y, line, font_h,
                           track_h, SOFT_WHITE, accent_tokens, ELECTRIC_BLUE)
        y += hlh

    if sub_lines:
        y += sub_gap - (hlh - size_h)  # tighten gap after headline
        for line in sub_lines:
            _draw_tracked_line(draw, line_x(line, font_s, track_s), y, line, font_s,
                               track_s, SOFT_WHITE, set(), SOFT_WHITE)
            y += slh

    base.convert("RGB").save(image_path)
    return True


def _accent_token_set(value) -> set[str]:
    if isinstance(value, list):
        raw = " ".join(str(v) for v in value)
    else:
        raw = str(value or "")
    return {
        t.strip(string.punctuation).lower()
        for t in raw.split()
        if t.strip(string.punctuation)
    }


def render_editorial_drop(image_path: pathlib.Path, visual: dict) -> bool:
    """Composite the bold condensed Layer8Culture social typography."""
    if not (BEBAS_NEUE_PATH.exists() and INTER_PATH.exists()):
        return False
    headline = str(visual.get("headline") or "").strip()
    if not headline:
        return False
    base = Image.open(image_path).convert("RGBA")
    w, h = base.size
    draw = ImageDraw.Draw(base)

    margin = int(w * 0.055)
    max_w = w - 2 * margin
    scale = _type_scale(w, h)
    accent_tokens = _accent_token_set(
        visual.get("accent_words") or visual.get("accent")
    )

    kicker = str(visual.get("kicker") or "").strip().upper()
    footer = str(visual.get("footer") or "").strip().upper()
    subtext = str(visual.get("subtext") or "").strip()
    layout = str(visual.get("layout") or "bottom_blast").strip()

    font_k = _load_font(INTER_PATH, max(18, int(scale * 0.025)), "Bold")
    font_h, size_h, track_h, lines_h = _fit_headline(
        draw,
        headline.upper(),
        max_w,
        start_size=int(scale * 0.145),
        min_size=int(scale * 0.060),
        max_lines=4,
    )
    if BEBAS_NEUE_PATH.exists():
        size = size_h
        while size >= int(scale * 0.058):
            candidate = ImageFont.truetype(str(BEBAS_NEUE_PATH), size)
            tracking = size * 0.005
            lines = _wrap(draw, headline.upper(), candidate, max_w, tracking)
            if len(lines) <= 4:
                font_h, size_h, track_h, lines_h = candidate, size, tracking, lines
                break
            size -= 2
    lines_h = _balance_lines(draw, headline.upper(), font_h, max_w, track_h, lines_h)

    # Supporting line, per brand/visual-style.md: Inter, sentence case, Soft White.
    # Shrink it to fit SUB_MAX_LINES rather than slicing the list, which used to
    # drop the tail of a long sentence mid-phrase.
    sub_lines: list[str] = []
    font_s = None
    size_s = max(20, int(scale * 0.030))
    if subtext:
        size = size_s
        floor = max(16, int(scale * 0.021))
        while True:
            font_s = _load_font(INTER_PATH, size, "Medium")
            sub_lines = _wrap(draw, subtext, font_s, max_w, size * 0.005)
            if len(sub_lines) <= SUB_MAX_LINES or size <= floor:
                break
            size -= 2
        size_s = size

    line_h = int(size_h * 0.86)
    sub_h = int(size_s * 1.30)
    sub_gap = int(scale * 0.020)
    kicker_h = int(scale * 0.050) if kicker else 0
    footer_h = max(14, int(scale * 0.018))

    # The footer is the lowest element, so it owns the safe margin and the type
    # block above reserves its lane. Both are derived from one measurement of the
    # real glyph box, so the reserved lane and the drawn position cannot drift.
    font_f = ImageFont.truetype(str(BEBAS_NEUE_PATH), footer_h) if footer else None
    footer_ink_bottom, footer_lane = 0, 0
    if font_f is not None:
        fbox = font_f.getbbox(footer)
        footer_ink_bottom = fbox[3]
        footer_lane = (fbox[3] - fbox[1]) + int(scale * 0.030)

    # Measure the block from exactly the values the drawing loop advances by, and
    # add the last line's real glyph depth. The previous version left the
    # pre-subtext gap and that depth out of block_h, so the type ran past the
    # bottom margin -- 2.9% clear of the edge on a 4.5% margin.
    block_h = kicker_h + len(lines_h) * line_h
    if sub_lines:
        block_h += sub_gap + (len(sub_lines) - 1) * sub_h
        block_h += _block_bottom(0, font_s, size_s * 0.005, sub_lines)
    else:
        block_h -= line_h
        block_h += _block_bottom(0, font_h, track_h, lines_h)

    safe_bottom = h - int(h * EDITORIAL_BOTTOM_MARGIN)
    top = max(int(h * 0.08), safe_bottom - footer_lane - block_h)

    card = layout == "top_text_media_card"
    if card:
        top = int(h * 0.085)

    # Type block is measured, so darken only what sits under it. alpha_composite
    # returns a new image, so the draw handle has to be rebuilt afterwards.
    base = _bottom_scrim(base, text_top=top)
    draw = ImageDraw.Draw(base)

    if card:
        card_margin = margin
        draw.rounded_rectangle(
            [card_margin, int(h * 0.34), w - card_margin, int(h * 0.90)],
            radius=int(w * 0.035),
            outline=(245, 245, 245, 80),
            width=max(2, int(w * 0.004)),
        )

    if kicker:
        draw.text((margin, top), kicker, font=font_k, fill=EDITORIAL_DIM)
        top += kicker_h

    y = top
    for line in lines_h:
        _draw_tracked_line(
            draw,
            margin,
            y,
            line,
            font_h,
            track_h,
            SOFT_WHITE,
            accent_tokens,
            ELECTRIC_BLUE,
        )
        y += line_h

    if sub_lines:
        y += sub_gap
        for line in sub_lines:
            _draw_tracked_line(
                draw,
                margin,
                y,
                line,
                font_s,
                size_s * 0.005,
                SOFT_WHITE,
                set(),
                SOFT_WHITE,
            )
            y += sub_h

    if font_f is not None:
        fw = draw.textlength(footer, font=font_f)
        draw.text(
            ((w - fw) / 2, safe_bottom - footer_ink_bottom),
            footer,
            font=font_f,
            fill=SOFT_WHITE,
        )

    base.convert("RGB").save(image_path)
    return True


def _decode_b64_image(result) -> bytes:
    """Extract and decode the base64 PNG bytes from an OpenAI images response."""
    b64 = result.data[0].b64_json
    return base64.b64decode(b64)


def typography_preset_for(account: str | None, visual: dict) -> str:
    preset = str(visual.get("typography_preset") or "").strip()
    if preset:
        return preset
    return "brand_title_card"


def _upscale_to_2k(path: pathlib.Path) -> None:
    """Upscale a rendered still so its long edge is ``IMAGE_LONG_EDGE`` px, keeping
    the native aspect ratio (LANCZOS). No-op when disabled or already at/above the
    target — gpt-image-2 maxes at a 1536px long edge, so this lifts stills to a 2K
    master before brand type is composited on top."""
    if not IMAGE_2K:
        return
    with Image.open(path) as im:
        im = im.convert("RGB")
        w, h = im.size
        long_edge = max(w, h)
        if long_edge >= IMAGE_LONG_EDGE:
            return
        scale = IMAGE_LONG_EDGE / long_edge
        im.resize((round(w * scale), round(h * scale)), Image.LANCZOS).save(path)


def _render_image(client, model: str, image_id: str, visual: dict,
                  account: str | None, out_dir: pathlib.Path) -> str | None:
    """Render one OpenAI image for ``visual``, composite branded typography,
    and return the written path (or None on API failure).

    Shared by every format: single posts, story frames, reel base stills, and each
    individual carousel slide. ``image_id`` becomes the output filename stem, so
    carousels pass ``<post_id>-<n>`` to write one file per slide.
    """
    prompt = visual.get("openai_prompt")
    if not prompt:
        return None
    aspect = visual.get("aspect", "1:1")
    size = ASPECT_SIZE.get(aspect, DEFAULT_SIZE)
    quality = visual.get("quality", IMAGE_QUALITY)
    if quality not in VALID_QUALITIES:
        print(f"  ! {image_id}: invalid quality {quality!r}, "
              f"using {IMAGE_QUALITY!r}")
        quality = IMAGE_QUALITY
    out_path = out_dir / f"{image_id}.png"
    try:
        image_bytes: bytes | None = None

        # Optional reference image: steer the look via the image edit endpoint.
        # NOTE: images.edit anchors the output to this exact reference, so reusing
        # one shared reference across posts makes every image come out nearly
        # identical. Style consistency should come from the BASE PROMPT in
        # brand/visual-style.md instead; only set style_reference when a post
        # genuinely needs to transform that specific source image. When it's
        # absent we use images.generate (below) for varied, topic-specific output.
        style_reference = visual.get("style_reference")
        if style_reference:
            ref_path = pathlib.Path(style_reference)
            if ref_path.exists():
                try:
                    with ref_path.open("rb") as ref_file:
                        result = client.images.edit(
                            model=model,
                            image=ref_file,
                            prompt=prompt,
                            size=size,
                            quality=quality,
                        )
                    image_bytes = _decode_b64_image(result)
                    print(f"  > {image_id}: used reference {ref_path} via images.edit "
                          f"(quality={quality})")
                except OpenAIError as e:
                    # The edit call failed (e.g. unsupported reference). Retry as
                    # a plain prompt-driven generation so the branded image still
                    # renders.
                    print(f"  ! {image_id}: reference edit failed ({e}); "
                          f"retrying without reference")
                    image_bytes = None
            else:
                print(f"  ! {image_id}: style_reference {ref_path} not found, "
                      f"generating without reference")

        if image_bytes is None:
            result = client.images.generate(
                model=model,
                prompt=prompt,
                size=size,
                quality=quality,
            )
            image_bytes = _decode_b64_image(result)

        out_path.write_bytes(image_bytes)

        # Upscale to a 2K master before laying brand type so typography is
        # composited at full resolution (gpt-image-2 caps at 1536px natively).
        try:
            _upscale_to_2k(out_path)
        except Exception as e:  # noqa: BLE001 - never lose a good image over upscale
            print(f"  ! {image_id}: 2K upscale skipped ({e})")

        # Composite branded headline typography (infographic / title-card style).
        # The image models render garbled text, so they're prompted to leave clean
        # negative space and we lay crisp brand type on top here.
        headline = visual.get("headline")
        if headline:
            try:
                if typography_preset_for(account, visual) == "editorial_drop":
                    applied = render_editorial_drop(out_path, visual)
                else:
                    applied = render_infographic(
                        out_path,
                        headline,
                        visual.get("subtext"),
                        visual.get("overlay_position", DEFAULT_OVERLAY_POSITION),
                        visual.get("accent"),
                    )
                if applied:
                    print(f"  > {image_id}: headline composited "
                          f"({headline[:48]!r})")
                else:
                    print(f"  ! {image_id}: fonts missing under assets/fonts, "
                          f"headline overlay skipped")
            except Exception as e:  # noqa: BLE001 - never lose a good image over text
                print(f"  ! {image_id}: headline overlay skipped ({e})")

        # Wordmark overlay is disabled by default. Backwards-compatible logo fields
        # are parsed but ignored while ACCOUNT_WORDMARK maps accounts to None.
        try:
            wordmark_path = ACCOUNT_WORDMARK.get(account)
            position = visual.get(
                "logo_position",
                ACCOUNT_LOGO_POSITION.get(account, DEFAULT_LOGO_POSITION),
            )
            # Opacity: explicit logo_opacity wins; else logo_subtle picks the
            # subtle preset; else fully opaque.
            if "logo_opacity" in visual:
                opacity = float(visual["logo_opacity"])
            elif visual.get("logo_subtle"):
                opacity = SUBTLE_LOGO_OPACITY
            else:
                opacity = DEFAULT_LOGO_OPACITY
            applied = composite_wordmark(
                out_path, aspect, position, opacity, wordmark_path
            )
            if applied:
                print(f"  > {image_id}: wordmark composited "
                      f"(position={position}, opacity={opacity:.2f})")
            elif wordmark_path is None:
                print(f"  > {image_id}: no wordmark configured, skipped overlay")
            else:
                print(f"  > {image_id}: wordmark asset missing, "
                      f"no overlay (would use position={position}, "
                      f"opacity={opacity:.2f})")
        except Exception as e:  # noqa: BLE001 - never lose a good image over branding
            print(f"  ! {image_id}: wordmark overlay skipped ({e})")
        print(f"  + {image_id} -> {out_path}")
        return str(out_path)
    except OpenAIError as e:
        # e.g. rate limit, billing, or other API errors — don't crash the whole
        # queue; let the caller fall back to the library for this post.
        print(f"  x {image_id}: OpenAI error ({e}), falling back to library")
        return None


def generate(client, model: str, post: dict, out_dir: pathlib.Path) -> str | None:
    """Render the single base still for a non-carousel post (single / story / reel).

    Stories and reels are vertical by nature, so default them to 9:16 when the
    generator didn't pin an aspect. For reels this still becomes the frame that
    scripts/reel_gen.py later animates into an mp4. Returns the written path.
    """
    visual = post["visual"]
    fmt = post.get("format", "single")
    if fmt in ("story", "reel") and "aspect" not in visual:
        visual = {**visual, "aspect": "9:16"}
    return _render_image(client, model, post["id"], visual, post.get("account"), out_dir)


def render_carousel(client, model: str, post: dict, out_dir: pathlib.Path) -> list[str] | None:
    """Render each slide of a carousel post as its own branded image.

    Returns the ordered list of written paths (``<post_id>-1.png`` …) or None if
    no slide produced an image. Each slide inherits the post-level visual defaults
    it doesn't override (aspect, quality, overlay/logo placement).
    """
    visual = post["visual"]
    slides = visual.get("slides") or []
    if not slides:
        print(f"  ! {post['id']}: carousel format but no visual.slides — skipping")
        return None
    paths: list[str] = []
    merged_slides = manual_media.carousel_slide_visuals(
        visual, IMAGE_QUALITY, DEFAULT_OVERLAY_POSITION)
    for i, merged in enumerate(merged_slides, 1):
        path = _render_image(client, model, f"{post['id']}-{i}", merged,
                             post.get("account"), out_dir)
        if path:
            paths.append(path)
        else:
            print(f"  ! {post['id']}: slide {i} failed to render")
    return paths or None


def run_manual(qpath: pathlib.Path, posts: list[dict],
               prompts_out: str | None = None,
               inbox: pathlib.Path = manual_media.DEFAULT_INBOX) -> None:
    """Write the copy-paste prompt pack instead of calling an image API.

    The queue is left untouched on purpose: nothing is marked "library" and no
    visual.file is claimed until scripts/manual_media_ingest.py has actually
    produced the image.
    """
    specs = manual_media.plan_images(posts, IMAGE_QUALITY, DEFAULT_OVERLAY_POSITION)
    pack = manual_media.write_prompt_pack(specs, qpath, prompts_out, inbox)
    inbox = pathlib.Path(inbox)
    inbox.mkdir(parents=True, exist_ok=True)
    print(f"Manual image mode: {len(specs)} image(s) to generate by hand.")
    for spec in specs:
        print(f"  - {spec.filename} ({spec.fmt}, {spec.aspect}, request {spec.size})")
    print(f"Prompt pack -> {pack}")
    print(f"Save the generated images into {inbox}/ , then run:")
    print(f"  python scripts/manual_media_ingest.py {qpath.as_posix()}")


def main(queue_file: str, manual: bool = False,
         prompts_out: str | None = None,
         inbox: pathlib.Path = manual_media.DEFAULT_INBOX) -> None:
    qpath = pathlib.Path(queue_file)
    posts = json.loads(qpath.read_text(encoding="utf-8"))
    out_dir = pathlib.Path("assets/generated")
    out_dir.mkdir(parents=True, exist_ok=True)

    if manual or MANUAL_BACKEND:
        return run_manual(qpath, posts, prompts_out, inbox)
    if not image_backend_available():
        missing = ("the openai package is not installed"
                   if not OPENAI_SDK_AVAILABLE
                   else "no AZURE_OPENAI_* or OPENAI_API_KEY credentials are set")
        print(f"No image backend available ({missing}); "
              f"falling back to manual (no-API) mode.")
        return run_manual(qpath, posts, prompts_out, inbox)

    client, model = _make_image_client()

    for post in posts:
        if post.get("visual", {}).get("source") != "openai":
            # Non-"openai" sources are intentionally skipped here: "library" posts
            # bring their own asset, and "reuse" cross-posts (e.g. TikTok reusing
            # the day's Instagram reel) get their media in reel_gen.py's pass 2.
            continue
        if post.get("format") == "carousel":
            paths = render_carousel(client, model, post, out_dir)
            if paths:
                post["visual"]["files"] = paths
                post["visual"]["file"] = paths[0]  # primary/cover for the publisher
                continue
        else:
            path = generate(client, model, post, out_dir)
            if path:
                post["visual"]["file"] = path
                continue
        # Either format failed to render — fall back to the library so the post
        # isn't blocked. (Reels overwrite visual.file with their mp4 later.)
        post["visual"]["source"] = "library"
        post["visual"].setdefault("library_hint", "default branded graphic")

    qpath.write_text(json.dumps(posts, indent=2), encoding="utf-8")
    print("Queue updated with generated visual paths.")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Generate branded visuals for a queue file, or (with "
                    "--manual) write a copy-paste image prompt pack for "
                    "hand-generation with no API.")
    parser.add_argument("queue_file", help="e.g. queue/2026-08-18.json")
    parser.add_argument(
        "--manual", action="store_true",
        help="skip the image API and write queue/<name>.prompts.md instead "
             "(same as IMAGE_BACKEND=manual)")
    parser.add_argument(
        "--prompts-out", default=None,
        help="override where the prompt pack is written")
    parser.add_argument(
        "--inbox", default=str(manual_media.DEFAULT_INBOX),
        help="folder to save hand-generated images into "
             f"(default: {manual_media.DEFAULT_INBOX})")
    args = parser.parse_args()
    main(args.queue_file, manual=args.manual, prompts_out=args.prompts_out,
         inbox=pathlib.Path(args.inbox))
